trigger:
  branches:
    include:
      - develop
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'  # Ajusta la versión de Node.js según tus necesidades
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install dependencies'

  - script: |
      npm run build  # Optional: if you have a build step
    displayName: 'Build project'

- job: DeployToProduction
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
  steps:
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'ServicioDinamica'  # Nombre de tu conexión de servicio
      appName: 'WebAppPoliDinamica'  # Nombre de tu App Service de producción
      package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    displayName: 'Deploy to Azure App Service'

- job: DeployToStaging
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'develop'))
  steps:
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'ServicioDinamica'  # Nombre de tu conexión de servicio
      appName: 'WebAppPoliDinamica'  # Nombre de tu App Service de staging
      package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    displayName: 'Deploy to Staging App Service'